books/urls.py
from django.conf.urls import url
from .views import index,detail,list

urlpatterns = [
    url(r'^index/', index,name='index'),
    url(r'^detail/(?P<book_id>\d+)/$',detail,name='detail'),
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)/$',list,name='list'),
 ]

bookstore/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^books/',include('books.urls',namespace='books')),#商品模块
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^order/',include('order.urls',namespace='order')),
    url(r'^comments/',include('comments.urls',namespace='comments')),
    url(r'^search/',include('haystack.urls',namespace='search')),
]

cart/urls.py
from django.conf.urls import url
from .views import cart_add,cart_count,cart_show,cart_del,cart_update

urlpatterns = [
    url(r'^cart_add/', cart_add,name='cart_add'),
    url(r'^cart_count/',cart_count,name='cart_count'),
    url(r'^cart_show/',cart_show,name='cart_show'),
	url(r'^cart_del/',cart_del,name='cart_del'),
	url(r'^cart_update/',cart_update,name='cart_update'),
 ]

users/urls.py
from django.conf.urls import url
from .views import register,register_handler,login,login_check,logout,user,address,order,verifycode,register_active

urlpatterns = [
    url(r'^register/', register,name='register'),
    url(r'^register_handler/',register_handler,name='register_handler'),
    url(r'^login/$',login,name='login'),
    url(r'^login_check/$',login_check,name='login_check'),
    url(r'^logout/$',logout,name='logout'),
    url(r'^user/$',user,name='user'),
    url(r'^address/',address,name='address'),
    url(r'^order/(?P<page>\d+)/$',order,name='order'),
    url(r'^verifycode/',verifycode,name='verifycode'),
    url(r'^active/(?P<token>.*)/$',register_active,name='active'),

]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	{% block title %}
    <title>尚硅谷书城-首页</title>
    {% endblock title %}
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
</head>

<body>
{% block header %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到尚硅谷书城!</div>
			<div class="fr">
                {% if request.session.islogin %}
				<div class="login_btn fl">
					欢迎您：<em>{{ request.session.username }}</em>
                    <a href="{% url 'users:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'users:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'users:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'users:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:cart_show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'users:order' page=1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header %}
    {% block search %}
	<div class="search_bar clearfix">
		<a href="{% url 'books:index' %}" class="logo fl"><img src="/static/images/logo.png" style="width: 160px; height: 53px;"></a>
		<div class="search_con fl">
             <form method="get" action="/search/">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
		<div class="guest_cart fr">
			<a href="javascript:;" class="cart_name fl">我的购物车</a>
			<div class="book_count fl" id="show_count">1</div>
		</div>
	</div>
    {% endblock search %}
    {% block top %}

    {% endblock top %}

	{% block content %}
    {% endblock content %}

    {% block footer %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京尚硅谷信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {% endblock footer %}
<script type="application/javascript">
    $.get('/cart/cart_count/',function (data) {
        //res是商品的总数
        $('#show_count').html(data.res);
    });
    $('.cart_name').click(function () {
        $.get('/cart/cart_show/',function (data) {
            if (data.res==0){
                alert(data.errmsg);
            }
            else{
                location.href ='/cart/cart_show/'
            }
        })
    });
</script>
{% block js %}
{% endblock js %}
</body>
</html>