books/urls.py
from django.conf.urls import url
from .views import index,detail,list

urlpatterns = [
    url(r'^index/', index,name='index'),
    url(r'^detail/(?P<book_id>\d+)/$',detail,name='detail'),
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)/$',list,name='list'),
 ]

bookstore/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^books/',include('books.urls',namespace='books')),#商品模块
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^order/',include('order.urls',namespace='order')),
    url(r'^comments/',include('comments.urls',namespace='comments')),
    url(r'^search/',include('haystack.urls',namespace='search')),
]

cart/urls.py
from django.conf.urls import url
from .views import cart_add,cart_count,cart_show,cart_del,cart_update

urlpatterns = [
    url(r'^cart_add/', cart_add,name='cart_add'),
    url(r'^cart_count/',cart_count,name='cart_count'),
    url(r'^cart_show/',cart_show,name='cart_show'),
	url(r'^cart_del/',cart_del,name='cart_del'),
	url(r'^cart_update/',cart_update,name='cart_update'),
 ]

users/urls.py
from django.conf.urls import url
from .views import register,register_handler,login,login_check,logout,user,address,order,verifycode,register_active

urlpatterns = [
    url(r'^register/', register,name='register'),
    url(r'^register_handler/',register_handler,name='register_handler'),
    url(r'^login/$',login,name='login'),
    url(r'^login_check/$',login_check,name='login_check'),
    url(r'^logout/$',logout,name='logout'),
    url(r'^user/$',user,name='user'),
    url(r'^address/',address,name='address'),
    url(r'^order/(?P<page>\d+)/$',order,name='order'),
    url(r'^verifycode/',verifycode,name='verifycode'),
    url(r'^active/(?P<token>.*)/$',register_active,name='active'),

]

users/models.py
from db.base_model import BaseModel
from django.db import models
from hashlib import sha1

def get_hash(str):
	'''取一个字符串的hash值'''
	sh = sha1()
	sh.update(str.encode('utf-8'))
	return sh.hexdigest()


class PassportManager(models.Manager):
	def add_one_passport(self,username,password,email):
		'''添加一个账户信息'''
		passport = self.create(username=username,password=get_hash(password),email=email)
		#返回password
		return passport

	def get_one_passport(self,username,password):
		'''根据用户密码查找账户的信息'''
		try:
			passport = self.get(username=username,password=get_hash(password))
		except self.model.DoesNotExist:
			#账户不存在
			passport = None
		return passport

	def check_passport(self,username):
		try:
			passport = self.get(username=username)
		except self.model.DoesNotExist:
			passport=None
		return passport


# Create your models here.
class Passport(BaseModel):
	'''用户模型类'''
	username = models.CharField(max_length=20,verbose_name='用户名称')
	password = models.CharField(max_length=40,verbose_name='用户密码')
	email = models.EmailField(verbose_name='用户邮箱')
	is_active = models.BooleanField(default=False,verbose_name='激活状态')

	#用户表的管管理器
	objects = PassportManager()

	class Meta:
		#指定数据库内的名称
		db_table = 's_user_account'
		verbose_name='用户'
		verbose_name_plural=verbose_name

	def __str__(self):
		return self.username


class AddressManeger(models.Manager):
	'''地址模型管理类'''
	def get_default_address(self,passport_id):
		'''查询指定用户的默认收货地址'''
		try:
			addr = self.get(passport_id=passport_id,is_default=True)
		except self.model.DoesNotExist:
			#没有默认的收货地址
			addr = None
		return addr

	def add_one_address(self,passport_id,recipient_name,recipient_addr,zip_code,recipient_phone):
		'''添加收货地址'''
		#判断用户是否有默认收货地址
		addr = self.get_default_address(passport_id=passport_id)
		if addr:
			#存在默认地址
			is_default = False
		else:
			#不存在默认地址
			is_default = True

		addr = self.create(passport_id=passport_id,recipient_name=recipient_name,recipient_addr=recipient_addr,zip_code=zip_code,recipient_phone=recipient_phone,is_default=is_default)

		return addr


class Address(BaseModel):
	'''地址模型类'''
	recipient_name = models.CharField(max_length=20,verbose_name='收件人')
	recipient_addr = models.CharField(max_length=256,verbose_name='收件地址')
	zip_code = models.CharField(max_length=6,verbose_name='邮政编码')
	recipient_phone = models.CharField(max_length=11,verbose_name='联系电话')
	is_default = models.BooleanField(default=False,verbose_name='是否默认')
	passport = models.ForeignKey('Passport',verbose_name='账户')

	objects = AddressManeger()

	class Meta:
		db_table='s_user_address'

users/views.py
import re
import json

from django.shortcuts import render,redirect
from django.urls import reverse
from django_redis import get_redis_connection

from .models import Passport,Address
from books.models import Books
from order.models import OrderInfo,OrderGoods
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from utils.decorators import login_required
from django.conf import settings
from django.core.mail import send_mail
from users.tasks import send_active_email
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import SignatureExpired
from django.http import HttpResponse
from django.core.paginator import Paginator
#itsdangerous 是一个产生token的库，有flask的作者编写

# Create your views here.
def register(request):
	'''显示用户注册界面'''
	return render(request,'users/register.html')

@csrf_exempt
def register_handler(request):
	'''进行用户注册'''
	#接收数据
	print(request.body)
	data = json.loads(request.body.decode('utf-8'))
	username = data.get('username')
	password = data.get('password')
	email = data.get('email')
	print("debug0:",username,password,email)
	#进行数据校验
	p = Passport.objects.check_passport(username=username)
	print("debug1:",p)
	if p:
		return JsonResponse({'res': '用户名已存在'})

	if not all([username,password,email]):
		return JsonResponse({'res':'参数不能为空'})

	# 判断邮箱是否合法
	if not re.match(r'^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', email):
		# 邮箱不合法
		return JsonResponse({'res': '邮箱不合法!'})
	#进行业务处理，添加一个账户
	passport =Passport.objects.add_one_passport(username,password,email)
	print("debug2:",passport)
	#生成激活的token itsdangrous
	serializer = Serializer(settings.SECRET_KEY,3600)
	token = serializer.dumps({'confirm':passport.id})
	print("debug3:",token)
	try:
	    token=token.decode()
	except Exception as e:
	    print("debug4:",e)
	print('123')
	#给用户的邮箱发送激活邮件
	#同步
	# send_mail('书城用户激活','',settings.EMAIL_FROM,[email],html_message='<a href="http://192.168.16.67:8000/users/active/%s/">http://192.168.16.67:8000/users/active/</a>'%token)

	#异步：使用redis celery 消息队列
	try:
	    send_active_email(token,username,email)
	except Exception as e:
	    print("debug5:",e)
	#注册后，返回到注册页面
	print("debug6:",111)
	return JsonResponse({'res':1})

def login(request):
	'''显示登录页面'''
	context={
		'username':'',
		'checked':'',
	}
	return render(request,'users/login.html',context)

@csrf_exempt
def login_check(request):
	data=json.loads(request.body.decode('utf-8'))
	username = data.get('username')
	password = data.get('password')
	remember = data.get('remember')
	verifycode=data.get('verifycode')
	#数据校验
	if verifycode.lower() !=request.session['verifycode']:
		return JsonResponse({'code':2})
	passport = Passport.objects.get_one_passport(username=username,password=password)
	jres = JsonResponse({'code':200})
	if passport:
		print("登录成功！")
		# 记住用户的登录状态
		print(remember,type(remember))
		if remember:
			#记住用户名
			jres.set_cookie('username',username,max_age=7*24*3600)
		else:
			#不记住
			jres.delete_cookie('username')
		request.session['islogin'] = True
		request.session['username'] = username
		request.session['passport_id'] = passport.id

		# return redirect(reverse('books:index'))
		return jres
	else:
		# p = Passport.objects.get_one_passport(username=username)
		# if not p:
		# 	return render(request,'users/login.html',{'errormsg':'用户名不存在'})
		# return render(request,'users/login.html',{'errormsg':'用户名或密码不正确'})
		return JsonResponse({'code':500})

def logout(request):
	request.session.flush()
	return redirect(reverse('books:index'))

#装饰器，需要登录才可以进入
@login_required
def user(request):
	'''用户中心－信息页'''
	passport_id = request.session.get('passport_id')
	#获取用户的基本信息
	addr = Address.objects.get_default_address(passport_id=passport_id)
	#获取用户的最近浏览信息
	con =get_redis_connection('default')
	key ='history_%d'%passport_id
	#取出用户最近浏览的５个商品的id
	history_li = con.lrange(key,0,4)
	book_li =[]
	for id in history_li:
		book = Books.objects.get_books_by_id(books_id=id)
		book_li.append(book)
	context = {
		'addr':addr,
		'page':'user',
		'book_li':book_li,
	}
	return render(request,'users/user_center_info.html',context)

@login_required
def address(request):
	'''用户中心－地址页'''
	#获取登录用户的id
	passport_id=request.session.get('passport_id')
	if request.method=='GET':
		#显示地址页面
		#查询用户的默认地址
		addr = Address.objects.get_default_address(passport_id=passport_id)
		return render(request,'users/user_center_site.html',{'addr':addr,'page':'address'})
	else:
		#添加收货地址
		#1.接收数据
		recipient_name = request.POST.get('username')
		recipient_addr = request.POST.get('addr')
		zip_code = request.POST.get('zip_code')
		recipient_phone = request.POST.get('phone')
		print(111)
		#2.进行校验
		if not all([recipient_name,recipient_addr,zip_code,recipient_phone]):
			return render(request,'users/user_center_site.html',{'errmsg':'参数不全'})

		#3.添加收货地址
		Address.objects.add_one_address(passport_id=passport_id,
										recipient_name=recipient_name,
										recipient_addr=recipient_addr,
										zip_code=zip_code,
										recipient_phone=recipient_phone)
		#4.返回应答
		return redirect(reverse('users:address'))

@login_required
def order(request,page):
	'''用户中心－订单页'''
	#查询用户的订单信息
	passport_id = request.session.get('passport_id')
	#获取订单信息
	order_li = OrderInfo.objects.filter(passport_id=passport_id)
	#分页
	paginator = Paginator(order_li,2)
	#获取分页后的总页数
	num_pages =paginator.num_pages
	#获取第page页是数据
	if page=='' or int(page) > num_pages:
		page =1
	else:
		page = int(page)
	# 返回值是一个Ｐａｇｅ类的实例对象
	order_li = paginator.page(page)
	# 进行页码控制
	# 1.总页数<5,显示所有页码
	# 2.当前页是前三页，显示１－５
	# 3.当前页是后３页，显示后５页
	# 4.其他情况，显示当前页前２页，后两页，当前页
	if num_pages <5:
		pages =range(1,num_pages+1)
	elif num_pages <3:
		pages = range(1,6)
	elif num_pages -page <=2:
		pages = range(num_pages-4,num_pages+1)
	else:
		pages=range(page-2,page+3)
	#遍历获取订单的商品信息
	#order->OrderInfo 实例对象
	for order in order_li:
		#根据订单id查询订单商品信息
		order_id = order.order_id
		order_books_li = OrderGoods.objects.filter(order_id=order_id)
		# order.status= OrderInfo.ORDER_STATUS_CHOICES[order.status-1][1]
		#计算商品的小计
		#order_books - >OrderGoods实例对象
		for order_books in order_books_li:
			count = order_books.count
			price = order_books.price
			amount = count*price
			#保存订单中每一个商品的小计
			order_books.amount =amount

		#给order对象动态增加一个属性order_books_li,保存订单中商品的信息
		order.order_books_li=order_books_li

	context ={
		'order_li':order_li,
		'page':'order',
		'pages':pages
	}
	return render(request,'users/user_center_order.html',context=context)


def verifycode(request):
	#引入绘图模式
	from PIL import Image,ImageDraw,ImageFont
	#引入随机函数模块
	import random
	#定义变量，用于画面的背景色，宽，高
	bgcolor = (random.randrange(20,100),random.randrange(20,100),255)
	width = 100
	height = 25
	#创建画面对象
	im = Image.new('RGB',(width,height),bgcolor)
	#创建画笔对象
	draw = ImageDraw.Draw(im)
	#调用画笔的point()函数绘制噪点
	for i in range(0,100):
		xy = (random.randrange(0,width),random.randrange(0,height))
		fill = (random.randrange(0,255),255,random.randrange(0,255))
		draw.point(xy,fill=fill)

	#定义验证码的备选值
	str1='1234567890qwertyuiopasdfghjklzxcvbnm'
	#随机选取４个值作为验证码
	rand_str=''
	for i in range(0,4):
		rand_str+=str1[random.randrange(0,len(str1))]
	#构造字体对象
	font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",15,encoding='unic')
	#构造字体颜色
	fontcolor = (255,random.randrange(0,255),random.randrange(0,255))
	#绘制４个字
	draw.text((5,2),rand_str[0],font=font,fill=fontcolor)
	draw.text((25,2),rand_str[1],font=font,fill=fill)
	draw.text((50,2),rand_str[2],font=font,fill=fill)
	draw.text((75,2),rand_str[3],font=font,fill=fill)

	#释放画笔
	del draw
	#存入session，用于做进一步的验证
	request.session['verifycode']=rand_str
	#内存文件操作
	import io
	buf = io.BytesIO()
	#将图片保存在内存中,文件类型为png
	im.save(buf,'png')
	#将内存中的图片数据返回给客户端，MIME类型为图片png
	return HttpResponse(buf.getvalue(),'image/png')


def register_active(request,token):
	'''用户账户激活'''
	serializer = Serializer(settings.SECRET_KEY,3600)
	try:
		info = serializer.loads(token)
		passport_id=info['confirm']
		#进行用户激活
		passport=Passport.objects.get(id=passport_id)
		passport.is_active=True
		passport.save()
		#跳转到登录页
		return redirect(reverse('users:login'))
	except SignatureExpired:
		#链接过期
		return HttpResponse('激活链接已过期')

templates/users/login.html
{% extends 'base.html' %}
{% block title %}
    <title>尚硅谷书城-登录</title>
{% endblock title %}
{% block header %}
{% endblock header %}
{% block search %}
{% endblock search %}

{% block content %}
	<div class="login_top clearfix">
		<a href="../books/index.html" class="login_logo"><img src="/static/images/logo.png" style="width: 160px; height: 53px;"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">学计算机 · 来尚硅谷</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/users/register/">立即注册</a>
				</div>
                <div class="clearfix">{{ errormsg }}</div>
				<div class="form_input">
{#					<form method="post" action="/users/login_check/">#}
                        {% csrf_token %}
						<input type="text" name="username" id="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" id="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
                        <div style="top:100px;position:absolute;">
                            <input type="text" id="vc" name="vc">
                            <img id="verifycode" src="/users/verifycode/" alt="checkcode"/>
                        </div>
						<input type="submit" name="" id="submit" value="登录" class="input_submit">
				</div>
			</div>
		</div>
	</div>
{% endblock content %}
    {% block js %}
<script type="application/javascript">
    $('#submit').click(function () {
        var username = $('#username').val();
        var password = $('#pwd').val();
        var csrf = $('input[name="csrfmiddlewaretoken"]').val()
        var remember = $('input[name="remember"]').prop('checked');
        console.log(remember)
        var vc =$('input[name="vc"]').val()
        data={
            'username':username,
            'password':password,
            'remember':remember,
            'csrfmiddlewaretoken':csrf,
            'verifycode':vc,
        }
        $.ajax({
            data:JSON.stringify(data),
            type:'POST',
            url:'/users/login_check/',
            //成功后的回调函数
            success:function (data) {
                if (data.code==200){
                    alert('登录成功！');
                    location.href='/books/index/';
                }
                else if (data.code ==2 ){
                    $("#username").next().html('验证码错误').show()
                }
                else{
                    alert('登录失败！')
                    $("#username").next().html('用户名或密码错误').show()
                }
            }
        });

    });
</script>
{% endblock js %}

templates/users/register.html
{% extends 'base.html' %}
{% block title %}
    <title>尚硅谷书城-注册</title>
{% endblock title %}
{% block header %}
{% endblock header %}
{% block search %}
{% endblock search %}

{% block content %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo.png" style="width: 160px; height: 53px;"></a>
			<div class="reg_slogan">学计算机  ·  来尚硅谷</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/users/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”尚硅谷书城用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
                    {{ errormsg }}
					<li class="reg_sub">
						<input type="submit" id="submit" value="注 册" name="">
                        <div id="res"></div>
					</li>
				</ul>
			</div>
		</div>

	</div>
    {% endblock content %}
{% block js %}
    <script type="application/javascript">
        $('#submit').click(function () {
            var username = $('#user_name').val();
            var password = $('#pwd').val();
            var email =$('#email').val();
            var data ={
                'username':username,
                'password':password,
                'email':email,
            };
	    console.log(username,password,email);
            $.ajax({
                data:JSON.stringify(data),
                type:'POST',
                url:'/users/register_handler/',
                success:function (data) {
                    if (data.res===1){
{#                        alert('注册成功！');#}
{#                        $('#submit').next().val('seccess');#}
                        //跳转到首页
                        location.href='/books/index/';
                    }
                    else{
                        console.log(data)
                        alert('注册失败！');
                        $("#user_name").next().html(data.res).show()
                    }
                },
                error:function (data) {
                    console.log('error');
                }
            })
        });
    </script>
{% endblock js %}

templates/users/user_center_info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    <title>尚硅谷书城-用户中心</title>
{% endblock title %}
{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'users:user' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'users:order' page=1%}">· 全部订单</a></li>
				<li><a href="{% url 'users:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ request.session.username }}</li>
							{% if addr %}
                            <li><span>联系方式：</span>{{ addr.recipient_phone }}</li>
							<li><span>联系地址：</span>{{ addr.recipient_addr }}</li>
						    {% else %}
                            <li><span>联系方式：</span>无</li>
							<li><span>联系地址：</span>无</li>
                            {% endif %}
                        </ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="book_type_list clearfix">
                        {% for book in book_li %}
                            <li>
                                <a href="{% url 'books:detail' book_id=book.id %}"><img src="{% static book.image %}"></a>
                                <h4><a href="{% url 'books:detail' book_id=book.id %}">{{ book.name }}</a></h4>
                                <div class="operate">
                                    <span class="prize">￥{{ book.price }}</span>
                                    <span class="unit">/{{ book.unit }}</span>
                                    <a href="javascript:;"  books_id="{{ book.id }}"class="add_book" title="加入购物车"></a>
                                </div>
                            </li>
                        {% empty %}
                            <span>暂无记录</span>
                        {% endfor %}
			</ul>
		</div>
		</div>
	</div>

{% endblock content %}
{% block js %}
    <script type="application/javascript">
		$('.add_book').click(function(){
		    var books_id=$(this).attr('books_id');
		    var book_count =1;
		    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
		    data={
		        'book_id':books_id,
                'book_count':book_count,
                'csrfmiddlewaretoken':csrf
            };
		    $.ajax({
		        data:JSON.stringify(data),
		        type:'POST',
                url:'/cart/cart_add/',
                success:function (data) {
                    console.log(data.code);
                    //添加成功
                    if (data.code==5) {
                        count = $('#show_count').html()
                        count = parseInt(count) + parseInt(book_count)
                        $('#show_count').html(count);
                    }
                    else{
                        //添加失败
                        alert(data.errmsg);
                    }
                }

            });

		});
    </script>
{% endblock js %}

templates/users/user_center_order.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load filters %}
{% block title %}
    <title>尚硅谷书城-用户中心</title>
{% endblock title %}

{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'users:user' %}">· 个人信息</a></li>
				<li><a href="{% url 'users:order' page=1%}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'users:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
            {% csrf_token %}
				<h3 class="common_title2">全部订单</h3>
                {% for order in order_li %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.create_time | date:"Y-m-d H:i:s" }}</li>
					<li class="col02">订单号：{{ order.order_id }}</li>
					<li class="col02 stress">{{ order.status | order_status}}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for order_books in order.order_books_li %}
								<ul class="order_book_list clearfix">					
									<li class="col01"><img src="{% static order_books.books.image %}"></li>
									<li class="col02">{{ order_books.books.name }}<em>{{ order_books.books.price }}元/{{ order_books.books.unit }}</em></li>
									<li class="col03">{{ order_books.count }}</li>
									<li class="col04">{{ order_books.amount }}元</li>
								</ul>
                                {% endfor %}
							</td>
							<td width="15%">{{ order.total_price }}元</td>
							<td width="15%">{{ order.status | order_status }}</td>
							<td width="15%"><a href="#" pay_method="{{ order.pay_method }}" order_id="{{ order.order_id }}" order_status="{{ order.status }}" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
        {% endfor %}

				<div class="pagenation">
                    {% if order_li.has_previous %}
					<a href="/users/order/{{ order_li.previous_page_number }}/">上一页</a>
                    {% endif %}
                    {% for pindex in pages %}
                        {% if pindex == order_li.number %}
                            <a href="/users/order/{{ pindex }}/" class="active">{{ pindex }}</a>
                        {% else %}
                            <a href="/users/order/{{ pindex }}/">{{ pindex }}</a>
                        {% endif %}
                    {% endfor %}
					{% if order_li.has_next %}
					<a href="/users/order/{{ order_li.next_page_number }}">下一页></a>
                    {% endif %}

				</div>
		</div>
	</div>


	<script type="application/javascript">
        $(function () {
            $('.oper_btn').click(function () {
                //获取订单id和订单的状态
                order_id = $(this).attr('order_id')
                order_status = $(this).attr('order_status')
                csrf = $('input[name="csrfmiddlewaretoken"]').val()
                params = {
                    'order_id':order_id,
                    'csrfmiddlewaretoken':csrf,
                }
                console.log(params,order_status)
                if (order_status == 1){
                    $.post('/order/order_pay/',params,function (data) {
                        if (data.res ==3){
                            //把用户引导支付页面
                            window.open(data.pay_url)
                            //查询用户的支付结果
                            $.post('/order/check_pay/',params,function (data) {
                                if (data.res==3){
                                    alert('支付成功')
                                    //重新刷新页面
                                    location.reload()
                                }
                                else if (data.res==1){
                                    alert(data.errmsg)
                                }
                                else if (data.res==2){
                                    alert(data.errmsg)
                                }
                                else{
                                    alert(data.errmsg)
                                }
                            })
                        }
                        else{
                            alert(data.errmsg)
                        }
                    })
                }
            });
        })
    </script>
{% endblock content %}

templates/users/user_center_site.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    <title>尚硅谷书城-用户中心</title>
{% endblock title %}

{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'users:user' %}">· 个人信息</a></li>
				<li><a href="{% url 'users:order' page=1%}">· 全部订单</a></li>
				<li><a href="{% url 'users:address' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
                        {% if addr %}
						<dd>{{ addr.recipient_addr }} （{{ addr.recipient_name }} 收） {{ addr.recipient_phone }}</dd>
					    {% else %}
                        <dd>无</dd>
                        {% endif %}
                    </dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post" action="/users/address/">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="username">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="addr"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock content %}